apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-data
data:
  DEMO_GREETING: "Hello from the environment"
  DEMO_FAREWELL: "Such a sweet sorrow"
---
apiVersion: v1
kind: Pod
metadata:
  name: env-var-demo-cm
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: demo
    image: docker.io/rkalluru/learnk8s:rhel9-bare
    env:
    - name: DEMO_GREETING
      valueFrom:
        configMapKeyRef:
          name: sample-data
          key: DEMO_GREETING
    - name: DEMO_FAREWELL
      valueFrom:
        configMapKeyRef:
          name: sample-data
          key: DEMO_FAREWELL
---
apiVersion: v1
kind: Pod
metadata:
  name: env-from-demo-cm
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: demo
    image: docker.io/rkalluru/learnk8s:rhel9-bare
    envFrom:
      - configMapRef:
          name: sample-data
---

# Values in k8s if it is string, then quotes are not mandatory. but if it is a integer then it is must.